# Generated by Django 5.2.3 on 2025-07-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_comment'),
        ('todo', '0002_task_description'),
    ]

    operations = [
    ]
